"""
Email model — one row per received email message.

Table: emails

Note: matter_key is intentionally nullable.  A freshly-ingested email has not
yet been assigned to a Matter; the resolution service writes matter_key later.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any, Dict, List, Optional

from sqlalchemy import ForeignKey, Index, String, Text, func, TIMESTAMP
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

if TYPE_CHECKING:
    from app.models.matter import Matter
    from app.models.case_brain_log import CaseBrainLog


class Email(Base):
    __tablename__ = "emails"

    # ------------------------------------------------------------------
    # Primary key — PostgreSQL UUID, generated by the DB
    # ------------------------------------------------------------------
    email_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Auto-generated UUID PK",
    )

    # ------------------------------------------------------------------
    # De-duplication handle
    # ------------------------------------------------------------------
    message_id: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="RFC 2822 Message-ID header value",
    )

    # ------------------------------------------------------------------
    # Matter linkage (nullable — resolved asynchronously)
    # ------------------------------------------------------------------
    matter_key: Mapped[Optional[str]] = mapped_column(
        String(50),
        ForeignKey("matters.matter_key", ondelete="SET NULL"),
        nullable=True,
    )

    # ------------------------------------------------------------------
    # Envelope fields
    # ------------------------------------------------------------------
    sender: Mapped[str] = mapped_column(
        String(320),
        nullable=False,
    )
    to_recipients: Mapped[Optional[List[Any]]] = mapped_column(
        JSONB,
        nullable=True,
        comment="List of {name, email} objects",
    )
    cc_recipients: Mapped[Optional[List[Any]]] = mapped_column(
        JSONB,
        nullable=True,
        comment="List of {name, email} objects",
    )

    # ------------------------------------------------------------------
    # Content
    # ------------------------------------------------------------------
    subject: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    body_text: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )
    received_at: Mapped[Optional[datetime]] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=True,
        comment="Original email Date header, timezone-aware",
    )

    # ------------------------------------------------------------------
    # Storage / processing
    # ------------------------------------------------------------------
    raw_file_path: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Path to the raw .eml file in data/emails/",
    )
    content_hash: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        comment="SHA-256 hex digest of the raw email for deduplication",
    )
    processing_status: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        comment="RECEIVED | PROCESSING | MATTER_IDENTIFIED | ANALYZED | COMPLETED | REVIEW_REQUIRED | FAILED",
    )

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    matter: Mapped[Optional["Matter"]] = relationship(
        "Matter",
        back_populates="emails",
    )
    brain_log_entries: Mapped[List["CaseBrainLog"]] = relationship(
        "CaseBrainLog",
        back_populates="email",
    )

    # ------------------------------------------------------------------
    # Indexes
    # ------------------------------------------------------------------
    __table_args__ = (
        Index("ix_emails_message_id", "message_id"),
        Index("ix_emails_matter_key", "matter_key"),
        Index("ix_emails_content_hash", "content_hash"),
        Index("ix_emails_processing_status", "processing_status"),
        Index("ix_emails_received_at", "received_at"),
    )

    def __repr__(self) -> str:
        return f"<Email {self.email_id} | {self.subject!r:.40}>"
