"""add_matter_events

Revision ID: 428b2ee93431
Revises: 9deb958978eb
Create Date: 2026-09-07 22:18:57.332929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '428b2ee93431'
down_revision: Union[str, None] = '9deb958978eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matter_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Event UUID primary key'),
    sa.Column('matter_key', sa.String(length=50), nullable=False, comment='FK to matters.matter_key'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='MATTER_CREATED | EMAIL_RECEIVED | EMAIL_ASSIGNED | CASE_BRAIN_UPDATED'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='MATTER | EMAIL | CASE_BRAIN'),
    sa.Column('source_reference', sa.String(length=500), nullable=True, comment='Optional source artefact identifier'),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='When the event actually happened'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this event record was created'),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Event-specific structured data'),
    sa.CheckConstraint("event_type IN ('MATTER_CREATED','EMAIL_RECEIVED','EMAIL_ASSIGNED','CASE_BRAIN_UPDATED')", name='ck_matter_events_event_type'),
    sa.CheckConstraint("source_type IN ('MATTER','EMAIL','CASE_BRAIN')", name='ck_matter_events_source_type'),
    sa.ForeignKeyConstraint(['matter_key'], ['matters.matter_key'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_matter_events_event_type', 'matter_events', ['event_type'], unique=False)
    op.create_index('ix_matter_events_matter_key', 'matter_events', ['matter_key'], unique=False)
    op.create_index('ix_matter_events_matter_key_occurred_at', 'matter_events', ['matter_key', 'occurred_at'], unique=False)
    op.create_index('ix_matter_events_occurred_at', 'matter_events', ['occurred_at'], unique=False)
    # Partial unique index: prevents duplicate events when source_reference is present.
    # Events without source_reference are NOT globally unique.
    op.create_index(
        'uq_matter_events_source_ref',
        'matter_events',
        ['source_type', 'source_reference', 'event_type'],
        unique=True,
        postgresql_where="source_reference IS NOT NULL",
    )
    op.alter_column('tasks', 'assigned_to',
                existing_type=sa.UUID(),
                comment='Assigned user UUID. FK cannot be enforced until the users table exists.',
                existing_comment='Assigned user UUID (users table not yet implemented)',
                existing_nullable=True)
    op.alter_column('tasks', 'created_by',
                existing_type=sa.UUID(),
                comment='Creator user UUID. Optional because authentication is not yet implemented. A future migration will make this NOT NULL and add a FK to users.user_id.',
                existing_comment='Creator user UUID (users table not yet implemented; auth pending)',
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_matter_events_source_ref', table_name='matter_events', postgresql_where="source_reference IS NOT NULL")
    op.alter_column('tasks', 'created_by',
                existing_type=sa.UUID(),
                comment='Creator user UUID (users table not yet implemented; auth pending)',
                existing_comment='Creator user UUID. Optional because authentication is not yet implemented. A future migration will make this NOT NULL and add a FK to users.user_id.',
                existing_nullable=True)
    op.alter_column('tasks', 'assigned_to',
                existing_type=sa.UUID(),
                comment='Assigned user UUID (users table not yet implemented)',
                existing_comment='Assigned user UUID. FK cannot be enforced until the users table exists.',
                existing_nullable=True)
    op.drop_index('ix_matter_events_occurred_at', table_name='matter_events')
    op.drop_index('ix_matter_events_matter_key_occurred_at', table_name='matter_events')
    op.drop_index('ix_matter_events_matter_key', table_name='matter_events')
    op.drop_index('ix_matter_events_event_type', table_name='matter_events')
    op.drop_table('matter_events')
    # ### end Alembic commands ###
