"""add_tasks

Revision ID: 9deb958978eb
Revises: c04fb1cff06a
Create Date: 2026-09-07 13:43:10.419477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9deb958978eb'
down_revision: Union[str, None] = 'c04fb1cff06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Task UUID primary key'),
    sa.Column('matter_key', sa.String(length=50), nullable=False, comment='FK to matters.matter_key'),
    sa.ForeignKeyConstraint(['matter_key'], ['matters.matter_key'], ondelete='RESTRICT'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='Short task title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed task description'),
    sa.Column('task_type', sa.String(length=30), nullable=False, comment='LEGAL | CLIENT | DOCUMENT | COMMUNICATION | FOLLOW_UP | FINANCIAL | ADMINISTRATIVE | OTHER'),
    sa.Column('status', sa.String(length=30), server_default='OPEN', nullable=False, comment='OPEN | IN_PROGRESS | WAITING | COMPLETED | CANCELLED'),
    sa.Column('priority', sa.String(length=30), server_default='MEDIUM', nullable=False, comment='LOW | MEDIUM | HIGH | URGENT'),
    sa.Column('assigned_to', sa.UUID(), nullable=True, comment='Assigned user UUID (users table not yet implemented)'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Creator user UUID (users table not yet implemented; auth pending)'),
    sa.Column('action_owner_type', sa.String(length=30), server_default='INTERNAL', nullable=False, comment='INTERNAL | CLIENT | EXTERNAL'),
    sa.Column('waiting_on', sa.String(length=30), nullable=True, comment='CLIENT | OPPOSING_COUNSEL | COURT | GOVERNMENT | PAYMENT | SIGNATURE | DOCUMENT | INTERNAL_APPROVAL | OTHER'),
    sa.Column('waiting_reason', sa.String(length=50), nullable=True, comment='Free-form reason when waiting'),
    sa.Column('waiting_since', sa.TIMESTAMP(timezone=True), nullable=True, comment='When the task entered WAITING state'),
    sa.Column('due_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When the task is expected to be completed'),
    sa.Column('next_action_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When the firm should take the next action'),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When the task was marked COMPLETED'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-modified timestamp'),
    sa.CheckConstraint("action_owner_type IN ('INTERNAL','CLIENT','EXTERNAL')", name='ck_tasks_action_owner_type'),
    sa.CheckConstraint("priority IN ('LOW','MEDIUM','HIGH','URGENT')", name='ck_tasks_priority'),
    sa.CheckConstraint("status IN ('OPEN','IN_PROGRESS','WAITING','COMPLETED','CANCELLED')", name='ck_tasks_status'),
    sa.CheckConstraint("task_type IN ('LEGAL','CLIENT','DOCUMENT','COMMUNICATION','FOLLOW_UP','FINANCIAL','ADMINISTRATIVE','OTHER')", name='ck_tasks_task_type'),
    sa.CheckConstraint("waiting_on IS NULL OR waiting_on IN ('CLIENT','OPPOSING_COUNSEL','COURT','GOVERNMENT','PAYMENT','SIGNATURE','DOCUMENT','INTERNAL_APPROVAL','OTHER')", name='ck_tasks_waiting_on'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('ix_tasks_assigned_to', 'tasks', ['assigned_to'], unique=False)
    op.create_index('ix_tasks_assigned_to_status_due_at', 'tasks', ['assigned_to', 'status', 'due_at'], unique=False)
    op.create_index('ix_tasks_matter_key', 'tasks', ['matter_key'], unique=False)
    op.create_index('ix_tasks_matter_key_status_due_at', 'tasks', ['matter_key', 'status', 'due_at'], unique=False)
    op.create_index('ix_tasks_next_action_at_actionable', 'tasks', ['next_action_at'], unique=False, postgresql_where="status IN ('OPEN', 'IN_PROGRESS', 'WAITING')")
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_waiting_next_action', 'tasks', ['waiting_on', 'waiting_reason', 'next_action_at'], unique=False, postgresql_where="status = 'WAITING'")
    op.alter_column('emails', 'processing_status',
               existing_type=sa.VARCHAR(length=40),
               comment='RECEIVED | PROCESSING | MATTER_IDENTIFIED | ANALYZED | COMPLETED | REVIEW_REQUIRED | FAILED',
               existing_comment='pending | processing | resolved | failed',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'processing_status',
               existing_type=sa.VARCHAR(length=40),
               comment='pending | processing | resolved | failed',
               existing_comment='RECEIVED | PROCESSING | MATTER_IDENTIFIED | ANALYZED | COMPLETED | REVIEW_REQUIRED | FAILED',
               existing_nullable=False)
    op.drop_index('ix_tasks_waiting_next_action', table_name='tasks', postgresql_where="status = 'WAITING'")
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_next_action_at_actionable', table_name='tasks', postgresql_where="status IN ('OPEN', 'IN_PROGRESS', 'WAITING')")
    op.drop_index('ix_tasks_matter_key_status_due_at', table_name='tasks')
    op.drop_index('ix_tasks_matter_key', table_name='tasks')
    op.drop_index('ix_tasks_assigned_to_status_due_at', table_name='tasks')
    op.drop_index('ix_tasks_assigned_to', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
