"""create_initial_schema

Revision ID: c04fb1cff06a
Revises: 
Create Date: 2026-08-14 09:44:31.908003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c04fb1cff06a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matters',
    sa.Column('matter_key', sa.String(length=50), nullable=False, comment='Business-level composite key, e.g. ACME-2024-001'),
    sa.Column('client_id', sa.String(length=30), nullable=False, comment='Client identifier'),
    sa.Column('matter_id', sa.String(length=30), nullable=False, comment='Matter identifier within the client'),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('matter_name', sa.String(length=200), nullable=False),
    sa.Column('practice_area', sa.String(length=100), nullable=True),
    sa.Column('matter_type', sa.String(length=100), nullable=True),
    sa.Column('matter_description', sa.String(length=500), nullable=False),
    sa.Column('matter_aliases_identifiers', sa.Text(), nullable=True, comment='Free-text aliases and alternative identifiers for fuzzy matching'),
    sa.Column('matter_status', sa.String(length=30), nullable=False, comment='open | closed | pending | suspended'),
    sa.Column('primary_attorney', sa.String(length=200), nullable=True),
    sa.Column('last_brain_update', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last time Case Brain was updated for this matter'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('matter_key')
    )
    op.create_index('ix_matters_client_id', 'matters', ['client_id'], unique=False)
    op.create_index('ix_matters_matter_status', 'matters', ['matter_status'], unique=False)
    op.create_table('emails',
    sa.Column('email_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Auto-generated UUID PK'),
    sa.Column('message_id', sa.String(length=500), nullable=True, comment='RFC 2822 Message-ID header value'),
    sa.Column('matter_key', sa.String(length=50), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('to_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of {name, email} objects'),
    sa.Column('cc_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of {name, email} objects'),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Original email Date header, timezone-aware'),
    sa.Column('raw_file_path', sa.Text(), nullable=False, comment='Path to the raw .eml file in data/emails/'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the raw email for deduplication'),
    sa.Column('processing_status', sa.String(length=40), nullable=False, comment='pending | processing | resolved | failed'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matter_key'], ['matters.matter_key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_index('ix_emails_content_hash', 'emails', ['content_hash'], unique=False)
    op.create_index('ix_emails_matter_key', 'emails', ['matter_key'], unique=False)
    op.create_index('ix_emails_message_id', 'emails', ['message_id'], unique=False)
    op.create_index('ix_emails_processing_status', 'emails', ['processing_status'], unique=False)
    op.create_index('ix_emails_received_at', 'emails', ['received_at'], unique=False)
    op.create_table('matter_participants',
    sa.Column('participant_id', sa.Integer(), autoincrement=True, nullable=False, comment='Surrogate auto-increment PK'),
    sa.Column('matter_key', sa.String(length=50), nullable=False),
    sa.Column('participant_name', sa.String(length=200), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('role_relationship', sa.String(length=100), nullable=True, comment='e.g. client, opposing_counsel, expert_witness'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['matter_key'], ['matters.matter_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_index('ix_matter_participants_email_address', 'matter_participants', ['email_address'], unique=False)
    op.create_index('ix_matter_participants_matter_key', 'matter_participants', ['matter_key'], unique=False)
    op.create_table('case_brain_log',
    sa.Column('brain_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matter_key', sa.String(length=50), nullable=False, comment='The matter this log entry describes'),
    sa.Column('email_id', sa.UUID(), nullable=True, comment='Source email, if any. Not unique — reprocessing allowed.'),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='When the event being logged actually occurred'),
    sa.Column('logged_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was written'),
    sa.Column('source_type', sa.String(length=30), nullable=False, comment='email | manual | system | import'),
    sa.Column('source_reference', sa.String(length=500), nullable=True, comment='Identifier of the source artefact, e.g. email Message-ID'),
    sa.Column('source_actor', sa.String(length=200), nullable=True, comment='Person or system that triggered this update'),
    sa.Column('update_summary', sa.Text(), nullable=False, comment='Human/AI-generated narrative of what changed'),
    sa.Column('logged_by', sa.String(length=200), nullable=True, comment='System component or user that wrote this entry'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.email_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_key'], ['matters.matter_key'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('brain_entry_id')
    )
    op.create_index('ix_case_brain_log_email_id', 'case_brain_log', ['email_id'], unique=False)
    op.create_index('ix_case_brain_log_matter_key', 'case_brain_log', ['matter_key'], unique=False)
    op.create_index('ix_case_brain_log_occurred_at', 'case_brain_log', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_brain_log_occurred_at', table_name='case_brain_log')
    op.drop_index('ix_case_brain_log_matter_key', table_name='case_brain_log')
    op.drop_index('ix_case_brain_log_email_id', table_name='case_brain_log')
    op.drop_table('case_brain_log')
    op.drop_index('ix_matter_participants_matter_key', table_name='matter_participants')
    op.drop_index('ix_matter_participants_email_address', table_name='matter_participants')
    op.drop_table('matter_participants')
    op.drop_index('ix_emails_received_at', table_name='emails')
    op.drop_index('ix_emails_processing_status', table_name='emails')
    op.drop_index('ix_emails_message_id', table_name='emails')
    op.drop_index('ix_emails_matter_key', table_name='emails')
    op.drop_index('ix_emails_content_hash', table_name='emails')
    op.drop_table('emails')
    op.drop_index('ix_matters_matter_status', table_name='matters')
    op.drop_index('ix_matters_client_id', table_name='matters')
    op.drop_table('matters')
    # ### end Alembic commands ###
